# Generated by Django 2.2.4 on 2019-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default=0, max_length=20)),
                ('password', models.CharField(default=0, max_length=20)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('china_count', models.IntegerField(default=0)),
                ('international_count', models.IntegerField(default=0)),
                ('entertainment_count', models.IntegerField(default=0)),
                ('sport_count', models.IntegerField(default=0)),
                ('technology_count', models.IntegerField(default=0)),
                ('military_count', models.IntegerField(default=0)),
            ],
        ),
    ]
