# Generated by Django 2.2.4 on 2019-10-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='abs_titles',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='sports',
            name='imgurls',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='sports',
            name='titles',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='sports',
            name='urls',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
